
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int MAS_MAS = 47;
  public static final int FUNCTION = 27;
  public static final int ASIGNAR = 43;
  public static final int MULT = 4;
  public static final int CONST = 16;
  public static final int CHAR = 21;
  public static final int DIFERENTE = 33;
  public static final int MENOS_MENOS = 48;
  public static final int DOS_PUNTOS = 28;
  public static final int INT = 22;
  public static final int DIV_IGUAL = 50;
  public static final int FOR = 40;
  public static final int WRITE = 54;
  public static final int NOT = 36;
  public static final int AND = 35;
  public static final int DIVICION = 5;
  public static final int OR = 34;
  public static final int IGUALAR = 17;
  public static final int DIV = 6;
  public static final int BEGIN = 10;
  public static final int NUM = 14;
  public static final int MAS_IGUAL = 45;
  public static final int IF = 37;
  public static final int PUNTO_COMA = 18;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int parc = 8;
  public static final int para = 7;
  public static final int error = 1;
  public static final int PROGRAM = 11;
  public static final int COMA = 19;
  public static final int CADENA = 13;
  public static final int MENOS = 3;
  public static final int MENOR = 32;
  public static final int MOD = 51;
  public static final int REAL = 24;
  public static final int MAYOR = 30;
  public static final int SHORTINT = 25;
  public static final int ELSE = 41;
  public static final int READ = 53;
  public static final int TO = 44;
  public static final int WHILE = 39;
  public static final int MAYOR_IGUAL = 29;
  public static final int POR_IGUAL = 49;
  public static final int THEN = 38;
  public static final int END = 9;
  public static final int STRING = 26;
  public static final int MENOR_IGUAL = 31;
  public static final int MENOS_IGUAL = 46;
  public static final int PROCEDURE = 52;
  public static final int LONGINT = 23;
  public static final int VAR = 12;
  public static final int DO = 42;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "MULT",
  "DIVICION",
  "DIV",
  "para",
  "parc",
  "END",
  "BEGIN",
  "PROGRAM",
  "VAR",
  "CADENA",
  "NUM",
  "ID",
  "CONST",
  "IGUALAR",
  "PUNTO_COMA",
  "COMA",
  "BOOLEAN",
  "CHAR",
  "INT",
  "LONGINT",
  "REAL",
  "SHORTINT",
  "STRING",
  "FUNCTION",
  "DOS_PUNTOS",
  "MAYOR_IGUAL",
  "MAYOR",
  "MENOR_IGUAL",
  "MENOR",
  "DIFERENTE",
  "OR",
  "AND",
  "NOT",
  "IF",
  "THEN",
  "WHILE",
  "FOR",
  "ELSE",
  "DO",
  "ASIGNAR",
  "TO",
  "MAS_IGUAL",
  "MENOS_IGUAL",
  "MAS_MAS",
  "MENOS_MENOS",
  "POR_IGUAL",
  "DIV_IGUAL",
  "MOD",
  "PROCEDURE",
  "READ",
  "WRITE"
  };
}

